add_newline = false

#prompt character
[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

#command duration
[cmd_duration]
disabled = true

# Disable the newline at the start of the prompt
[line_break]
disabled = true

[package]
disabled = true

#username displaying in ssh sessions
[username]
format = "[$user]($style)[@](bold green)"

#hostname displaying in ssh sessions
[hostname]
format = "[$hostname]($style):"
trim_at = "-"

#battery stuff
#[[battery.display]]
threshold = 25
style = "bold red"

[jobs]
symbol = " "
#symbol = " "
#java version display
[java]
format = "via [${version} ](bold red)"

#python version display
[python]
format = "via [${version} ](bold green)"

[git_branch]
symbol=" "

# custom haskell module
[custom.haskell]
shell = ["ghci","--version","|","awk",'-F" "', "{ pint $8 }"]
symbol = ""
lambda = "λ"
format = "[${symbol} 8.0.2 ](blue bold)"
extensions = ["hs"]

#custom c mode
[custom.c]
shell = ["gcc","--version"]
symbol = ""
format = "[${symbol} ](bold red)"
extensions = ["c"]

#custom c++ mode
[custom.cpp]
shell = ["g++","--version"]
symbol = ""
format = "[${symbol} ](bold red)"
extensions = ["cpp","h","cxx","hpp","hxx"]

